repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # - id: no-commit-to-branch
      #   args: [--branch=main]
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
        exclude: ^.vscode/
      - id: pretty-format-json
        exclude: ^.vscode/
        args: [--autofix]
      - id: check-xml
      - id: debug-statements
      - id: check-added-large-files
      - id: check-case-conflict
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]



  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports
          - --ignore-init-module-imports

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort



  - repo: local
    hooks:
      - id: mypy_check
        name: run mypy
        entry: mypy backend/app
        language: system
        pass_filenames: false
        types: [python]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ["--fix"]


default_language_version:
  python: python3.12



fail_fast: true

exclude: tests/data
